on:
  push:
    branches:
      - main
  workflow_dispatch:
    
env:
  TODOLIST_BACKEND_URL: http://localhost:8080
  WEBSITE_URL: http://localhost:3000
  SERVER_URL: http://localhost:4000
  PORT: 4000
  SEND_VERIFICATION_EMAIL_URL: "127.0.0.1"
  SMTP_PORT: 3005
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
  SMTP_MAIL: ${{ secrets.SMTP_MAIL }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ENV_FILE
    steps:
      - uses: actions/checkout@v4
        with:
          path: main
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Start MongoDB 6.0
        uses: supercharge/mongodb-github-action@1.9.0
        
      - name: Checkout the user_management repo
        uses: actions/checkout@v4
        with:
          repository: Scrice994/NextJSTodolistUserManagement
          path: user_management

      - name: Start user_management server
        run: |
          cd user_managment
          npm ci
          npm run build
          npm start &

      - name: start bff and run tests
        run: |
          cd main
          npm ci
          npm run test
          npm run build
          npm start &
          npm run test:api

        